export const GET_VOTERS = "GET_VOTERS";
export const GET_VOTERS_SUCCESS = "GET_VOTERS_SUCCESS";
export const GET_VOTERS_FAIL = "GET_VOTERS_FAIL";

export const GET_VOTERS_TABLE_COLUMN_NAMES = "GET_VOTERS_TABLE_COLUMN_NAMES"
export const GET_VOTERS_TABLE_COLUMN_NAMES_SUCCESS = "GET_VOTERS_TABLE_COLUMN_NAMES_SUCCESS"
export const GET_VOTERS_TABLE_COLUMN_NAMES_FAIL = "GET_VOTERS_TABLE_COLUMN_NAMES_FAIL"

export const ADD_VOTERS = "ADD_VOTERS"
export const ADD_VOTERS_SUCCESS = "ADD_VOTERS_SUCCESS"
export const ADD_VOTERS_FAIL = "ADD_VOTERS_FAIL"

export const UPDATE_VOTERS = "UPDATE_VOTERS"
export const UPDATE_VOTERS_SUCCESS = "UPDATE_VOTERS_SUCCESS"
export const UPDATE_VOTERS_FAIL = "UPDATE_VOTERS_FAIL"

export const DELETE_VOTERS = "DELETE_VOTERS"
export const DELETE_VOTERS_SUCCESS = "DELETE_VOTERS_SUCCESS"
export const DELETE_VOTERS_FAIL = "DELETE_VOTERS_FAIL"

export const ON_ACTIVATE_DEACTIVATE_VOTERS = "ON_ACTIVATE_DEACTIVATE_VOTERS"
export const ON_ACTIVATE_DEACTIVATE_VOTERS_SUCCESS = "ON_ACTIVATE_DEACTIVATE_VOTERS_SUCCESS"
export const ON_ACTIVATE_DEACTIVATE_VOTERS_FAIL = "ON_ACTIVATE_DEACTIVATE_VOTERS_FAIL"

export const ON_ACTIVATE_VOTERS = "ON_ACTIVATE_VOTERS"
export const ON_ACTIVATE_VOTERS_SUCCESS = "ON_ACTIVATE_VOTERS_SUCCESS"
export const ON_ACTIVATE_VOTERS_FAIL = "ON_ACTIVATE_VOTERS_FAIL"


