export const GET_REFER_VOTERS = "GET_REFER_VOTERS";
export const GET_REFER_VOTERS_SUCCESS = "GET_REFER_VOTERS_SUCCESS";
export const GET_REFER_VOTERS_FAIL = "GET_REFER_VOTERS_FAIL";


export const GET_REFER_VOTERS_TABLE_COLUMN_NAMES = "GET_REFER_VOTERS_TABLE_COLUMN_NAMES"
export const GET_REFER_VOTERS_TABLE_COLUMN_NAMES_SUCCESS = "GET_REFER_VOTERS_TABLE_COLUMN_NAMES_SUCCESS"
export const GET_REFER_VOTERS_TABLE_COLUMN_NAMES_FAIL = "GET_REFER_VOTERS_TABLE_COLUMN_NAMES_FAIL"

export const ADD_REFER_VOTERS = "ADD_REFER_VOTERS"
export const ADD_REFER_VOTERS_SUCCESS = "ADD_REFER_VOTERS_SUCCESS"
export const ADD_REFER_VOTERS_FAIL = "ADD_REFER_VOTERS_FAIL"

export const UPDATE_REFER_VOTERS = "UPDATE_REFER_VOTERS"
export const UPDATE_REFER_VOTERS_SUCCESS = "UPDATE_REFER_VOTERS_SUCCESS"
export const UPDATE_REFER_VOTERS_FAIL = "UPDATE_REFER_VOTERS_FAIL"

export const DELETE_REFER_VOTERS = "DELETE_REFER_VOTERS"
export const DELETE_REFER_VOTERS_SUCCESS = "DELETE_REFER_VOTERS_SUCCESS"
export const DELETE_REFER_VOTERS_FAIL = "DELETE_REFER_VOTERS_FAIL"

export const ON_ACTIVATE_DEACTIVATE_REFER_VOTERS = "ON_ACTIVATE_DEACTIVATE_REFER_VOTERS"
export const ON_ACTIVATE_DEACTIVATE_REFER_VOTERS_SUCCESS = "ON_ACTIVATE_DEACTIVATE_REFER_VOTERS_SUCCESS"
export const ON_ACTIVATE_DEACTIVATE_REFER_VOTERS_FAIL = "ON_ACTIVATE_DEACTIVATE_REFER_VOTERS_FAIL"



